# Agenda

- Data frames
    - Creating
    - Retrieving
    - Methods (series methods and special data frame methods)
- Loading data
    - CSV
    - Excel
    - Downloading from the Internet (retrieving files and scraping sites)

In [2]:
import pandas as pd
from pandas import Series, DataFrame

In [3]:
# create a series based on any iterable in Python (usually a list or a NumPy array)
# we can pass additional keyword arguments, especially index and dtype

# Data frames are similar; we can pass a 2D set of values (a list of lists or a 2D NumPy array), and
# also index, and also columns -- the names of the columns we want

In [4]:
df = DataFrame([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90],
                [100, 110, 120]])
df

0    1    2
0   10   20   30
1   40   50   60
2   70   80   90
3  100  110  120

In [5]:
type(df)

pandas.core.frame.DataFrame

# Our basic data frame

- A data frame has rows and columns
- The rows are identified with the index (i.e, the same index that we had on our series)
- The columns are identified with names that we just call "columns"

The key thing to remember: Each column is a Pandas series!

- I can retrieve a row with `.loc` or `.iloc`, as before
- I can retrieve a column with `[]` and the column's name

In [6]:
df.loc[1]

0    40
1    50
2    60
Name: 1, dtype: int64

In [7]:
df[1]  # this will retrieve the column

0     20
1     50
2     80
3    110
Name: 1, dtype: int64

In [8]:
%timeit df.loc[1]

11.4 μs ± 129 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [9]:
%timeit df.iloc[1]

10.3 μs ± 120 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [10]:
%timeit df[1]

1.33 μs ± 17.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [11]:
# behind the scenes of our data frame is actually a 2D NumPy array (in theory)

df.values

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [12]:
# we can retrieve in all of the ways we've already seen!

df.loc[[1, 3]]  # fancy indexing

0    1    2
1   40   50   60
3  100  110  120

In [13]:
df[[0, 1]]  # here, we retrieve two columns

0    1
0   10   20
1   40   50
2   70   80
3  100  110

In [14]:
# if I retrieve one row, or one column, then I get a series
df[1]

0     20
1     50
2     80
3    110
Name: 1, dtype: int64

In [15]:
df

0    1    2
0   10   20   30
1   40   50   60
2   70   80   90
3  100  110  120

In [16]:
# We can name the index and the columns via keyword arguments when we create the data frame

df = DataFrame([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90],
                [100, 110, 120]],
              index=list('abcd'),
              columns=list('xyz'))
df

x    y    z
a   10   20   30
b   40   50   60
c   70   80   90
d  100  110  120

- Row names (just like the index in a series) can repeat, and that's even useful!
- Column names cannot repeat (like the keys in a dict)

You can even think of a data frame as a dict of series, where the keys are the column names and the values are Pandas series objects.

In [17]:
df.loc['b']

x    40
y    50
z    60
Name: b, dtype: int64

In [18]:
df.iloc[2]

x    70
y    80
z    90
Name: c, dtype: int64

In [19]:
df['x']

a     10
b     40
c     70
d    100
Name: x, dtype: int64

In [20]:
df.loc[['a', 'b']]

x   y   z
a  10  20  30
b  40  50  60

In [21]:
df[['x', 'z']]

x    z
a   10   30
b   40   60
c   70   90
d  100  120

In [22]:
# if I retrieve a series, then I can run a method on it

df['x'].mean()

np.float64(55.0)

In [23]:
df['x'].describe()

count      4.000000
mean      55.000000
std       38.729833
min       10.000000
25%       32.500000
50%       55.000000
75%       77.500000
max      100.000000
Name: x, dtype: float64

In [25]:
# I can do that for the rows

df.loc['b'].describe()

count     3.0
mean     50.0
std      10.0
min      40.0
25%      45.0
50%      50.0
75%      55.0
max      60.0
Name: b, dtype: float64

As a general rule, any method that we can run on a series can also be run on a data frame. We'll get one result per column, and the results will either be a series (if we get one value per column) or a data frame (if we get a series back from the method).

In [26]:
df.mean()   # this will calculate the mean for each column

x    55.0
y    65.0
z    75.0
dtype: float64

In [27]:
df.describe()   # this will invoke describe on each column

x           y           z
count    4.000000    4.000000    4.000000
mean    55.000000   65.000000   75.000000
std     38.729833   38.729833   38.729833
min     10.000000   20.000000   30.000000
25%     32.500000   42.500000   52.500000
50%     55.000000   65.000000   75.000000
75%     77.500000   87.500000   97.500000
max    100.000000  110.000000  120.000000

In [28]:
df

x    y    z
a   10   20   30
b   40   50   60
c   70   80   90
d  100  110  120

In [30]:
# we've seen how we can retrieve either a row or a column.
# but how can we retrieve an individual value?

df.loc['b'].loc['y']

np.int64(50)

In [31]:
# even worse:

df.loc['b']['y']

np.int64(50)

In [32]:
# better is to use the 2-argument version of .loc, where you specify the row and the column

df.loc['b', 'y']

np.int64(50)

In [33]:
df.sum()

x    220
y    260
z    300
dtype: int64

In [34]:
# what if I want to sum across the rows?

df.sum(axis='columns')

a     60
b    150
c    240
d    330
dtype: int64

In [35]:
df = DataFrame([[10, 20, 30.5],
                [40, 50, 60],
                [70, 80, 90],
                [100, 110, 120]],
              index=list('abcd'),
              columns=list('xyz'))
df

x    y      z
a   10   20   30.5
b   40   50   60.0
c   70   80   90.0
d  100  110  120.0

In [36]:
df.dtypes   # get the dtype of each column

x      int64
y      int64
z    float64
dtype: object

In [37]:
# what happens when we retrieve row 'c'?

df.loc['c']

x    70.0
y    80.0
z    90.0
Name: c, dtype: float64

In [38]:
# what if I want to assign back to a value?

# this is a bad way to do it, as you'll see!
df.loc['c'].loc['z'] = 999 

/var/folders/rr/0mnyyv811fs5vyp22gf4fxk00000gn/T/ipykernel_26269/590399145.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df.loc['c'].loc['z'] = 999
/var/folders/rr/0mnyyv811fs5vyp22gf4fxk00000gn/T/ipykernel_26269/590399145.py:4: Settin

In [39]:
df

x    y      z
a   10   20   30.5
b   40   50   60.0
c   70   80   90.0
d  100  110  120.0

In [40]:
# the solution is always to use the two-argument version of .loc,
# which guarantees that we'll assign back to the original data frame

df.loc['c', 'z'] = 999 

In [41]:
df

x    y      z
a   10   20   30.5
b   40   50   60.0
c   70   80  999.0
d  100  110  120.0

# Exercise: Simple data frame

1. Create a 5x5 data frame in which the rows are `abcde` and the columns are `vwxyz`. The values can be random integers from 0-1,000. (You can use a 2D NumPy array to initialize the values.)
2. Retrieve row `b`
3. Retrieve rows `b` and `d`
4. Retrieve rows `b`, `c`, and `d`
5. Retrieve column `w`
6. Retrieve columns `w` and `y`
7. Retrieve columns `w`, `x`, and `y`
8. Retrieve the item at row `e`, column `v`
9. Update the value at row e`, column `z` to be 123.456

In [42]:
import numpy as np

np.random.randint(0, 1000, 20).reshape(4, 5)

array([[ 92, 855, 155, 443, 455],
       [386, 725, 796, 590, 586],
       [756, 567, 363, 394, 451],
       [449, 357,   3, 378, 714]])

In [43]:
np.random.randint(0, 1000, [4,5])

array([[444, 675, 888, 800, 967],
       [174, 391, 834, 520, 112],
       [976, 750, 342, 754, 295],
       [367, 243, 289, 455,  79]])

In [44]:
np.random.seed(0)

df = DataFrame(np.random.randint(0, 1000, [5,5]),
               index=list('abcde'),
               columns=list('vwxyz'))
df

v    w    x    y    z
a  684  559  629  192  835
b  763  707  359    9  723
c  277  754  804  599   70
d  472  600  396  314  705
e  486  551   87  174  600

In [45]:
# Retrieve row b

df.loc['b']

v    763
w    707
x    359
y      9
z    723
Name: b, dtype: int64

In [46]:
%timeit df.loc['b']

12.2 μs ± 70 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [47]:
%timeit df.iloc[1]

10.6 μs ± 177 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [48]:
# Retrieve rows b and d

df.loc[['b', 'd']]

v    w    x    y    z
b  763  707  359    9  723
d  472  600  396  314  705

In [49]:
# Retrieve rows b, c, and d

df.loc['b':'d']  # use a slice, up to and including (with df.loc)

v    w    x    y    z
b  763  707  359    9  723
c  277  754  804  599   70
d  472  600  396  314  705

In [52]:
# Retrieve column w

%timeit df['w']

1.57 μs ± 10.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [53]:
# you can also use a different syntax, "dot syntax," to retrieve a column

%timeit df.w

2.92 μs ± 21 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [54]:
# Retrieve columns w and y

df[['w', 'y']]

w    y
a  559  192
b  707    9
c  754  599
d  600  314
e  551  174

In [55]:
# Retrieve columns w, x, and y

df[['w', 'x', 'y']]

w    x    y
a  559  629  192
b  707  359    9
c  754  804  599
d  600  396  314
e  551   87  174

In [56]:
df['w':'y']  # if you give a slice to [], Pandas looks for that slice ON THE ROWS!

Empty DataFrame
Columns: [v, w, x, y, z]
Index: []

In [57]:
# Retrieve the item at row e, column v

df.loc[ 'e',    # row selector
        'v']    # column selector


np.int64(486)

In [58]:
df.loc[ ['b', 'e']   # row selector is two rows
    ,
        ['v', 'z']   # column selector
]

v    z
b  763  723
e  486  600

In [59]:
# Update the value at row e, column z` to be 123.456

df.loc['e', 'z'] = 123.456

/var/folders/rr/0mnyyv811fs5vyp22gf4fxk00000gn/T/ipykernel_26269/3297010828.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '123.456' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc['e', 'z'] = 123.456


In [60]:
df.dtypes

v      int64
w      int64
x      int64
y      int64
z    float64
dtype: object

In [61]:
# how should we update that column/value to avoid the problem?
# answer: replace the column with a new version of itself using float

np.random.seed(0)

df = DataFrame(np.random.randint(0, 1000, [5,5]),
               index=list('abcde'),
               columns=list('vwxyz'))
df

v    w    x    y    z
a  684  559  629  192  835
b  763  707  359    9  723
c  277  754  804  599   70
d  472  600  396  314  705
e  486  551   87  174  600

In [62]:
df.dtypes

v    int64
w    int64
x    int64
y    int64
z    int64
dtype: object

In [63]:
# you can add a new column to a data frame via assignment
df['u'] = [10, 20, 30, 40, 50]   # needs to be the same length as the other columns

df

v    w    x    y    z   u
a  684  559  629  192  835  10
b  763  707  359    9  723  20
c  277  754  804  599   70  30
d  472  600  396  314  705  40
e  486  551   87  174  600  50

In [64]:
# what if I assign to a column that already exists? It's replaced.

df['u'] = [100 ,200, 300, 400, 500]
df

v    w    x    y    z    u
a  684  559  629  192  835  100
b  763  707  359    9  723  200
c  277  754  804  599   70  300
d  472  600  396  314  705  400
e  486  551   87  174  600  500

In [65]:
# I can do the same, but using the output of .astype

df['u'] = df['u'].astype(np.float64)
df

v    w    x    y    z      u
a  684  559  629  192  835  100.0
b  763  707  359    9  723  200.0
c  277  754  804  599   70  300.0
d  472  600  396  314  705  400.0
e  486  551   87  174  600  500.0

In [66]:
df.loc['e', 'u'] = 123.456


In [67]:
df

v    w    x    y    z        u
a  684  559  629  192  835  100.000
b  763  707  359    9  723  200.000
c  277  754  804  599   70  300.000
d  472  600  396  314  705  400.000
e  486  551   87  174  600  123.456

# Other ways to create data frames

You aren't going to be creating a *lot* of data frames manually; most will be based on data you read from elsewhere. But let's just look at a few techniques we can use for when you do need to create them.

1. List of lists (we've seen this)
2. List of dicts (the keys indicate which columns we're adding to)
3. Dict of lists (the keys indicate the column names, and the lists are the values)
4. Dict of series (same as above, but using a series rather than a list)

In [70]:
# list of dicts
# the union of all keys across all lists will be our column names
# any missing key-value intersection is given nan as a value

df = DataFrame([{'a':10, 'b':20, 'c':30},
                {'a':100, 'b':200, 'c':300},
                {'a':1000, 'b':2000, 'd':4000}],
              index=list('xyz'))
df

a     b      c       d
x    10    20   30.0     NaN
y   100   200  300.0     NaN
z  1000  2000    NaN  4000.0

In [72]:
# dict of lists
# here, we're just defining the data frame as as dict whose values are lists/series

df = DataFrame({'a':[10, 20, 30, 40, 50],
                'b':[100, 200, 300, 400, 500],
                'c':[1000, 2000, 3000, 4000, 5000]},
              index=list('vwxyz'))
df

a    b     c
v  10  100  1000
w  20  200  2000
x  30  300  3000
y  40  400  4000
z  50  500  5000

In [73]:
# what happens if a data frame has repeated column names?

df = DataFrame(np.random.randint(0, 100, [3, 3]),
               index=list('aab'),
               columns=list('xyy'))
df

x   y   y
a  81  37  25
a  77  72   9
b  20  80  69

In [74]:
df['y']

y   y
a  37  25
a  72   9
b  80  69

In [75]:
df['y'] = [10, 20, 30]
df

x   y   y
a  81  10  10
a  77  20  20
b  20  30  30

In [77]:
df.columns.duplicated()

array([False, False,  True])

# Exercise: Semi-realistic example

1. Create a data frame with two columns, `age` and `shoesize`. Each row will represent a different person in your family. The index for each row should be the name of the person, and the two columns should be the age and shoe size for that person. Create this twice, first using a list of dicts and then using a dict of lists.
2. What is the mean age in your family? How much does this differ from the median? Ask the same about the shoe size. 

In [80]:
# list of dicts -- we describe the rows

df = DataFrame([{'age': 23, 'shoesize':40},
                {'age': 21, 'shoesize': 40},
                {'age': 19, 'shoesize':44},
                {'age': 54, 'shoesize':46}],
              index=['Atara', 'Shikma', 'Amotz', 'Reuven'])
df

age  shoesize
Atara    23        40
Shikma   21        40
Amotz    19        44
Reuven   54        46

In [81]:
df.loc['Reuven']

age         54
shoesize    46
Name: Reuven, dtype: int64

In [82]:
# create this as a dict of lists

df = DataFrame({'age':[23, 21, 19, 54],
                'shoesize':[40, 40, 44, 46]},
               index=['Atara', 'Shikma', 'Amotz', 'Reuven'])
df

age  shoesize
Atara    23        40
Shikma   21        40
Amotz    19        44
Reuven   54        46

In [83]:
df['age'].mean()

np.float64(29.25)

In [84]:
df['age'].median()

np.float64(22.0)

In [85]:
df['shoesize'].mean()

np.float64(42.5)

In [86]:
df['shoesize'].median()

np.float64(42.0)

In [87]:
df.mean()

age         29.25
shoesize    42.50
dtype: float64

In [88]:
df.median()

age         22.0
shoesize    42.0
dtype: float64

In [89]:
df.describe()

age  shoesize
count   4.000000       4.0
mean   29.250000      42.5
std    16.580611       3.0
min    19.000000      40.0
25%    20.500000      40.0
50%    22.000000      42.0
75%    30.750000      44.5
max    54.000000      46.0

In [91]:
# df.describe returns a data frame!
# I can choose which rows I want

df.describe().loc[['mean', '50%']]

age  shoesize
mean  29.25      42.5
50%   22.00      42.0

In [93]:
%timeit df.describe().loc[['mean', '50%']]

1.39 ms ± 33.6 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [92]:
# the 'agg' method lets us run more than one aggregation method, and returns the results for all
df.describe().agg(['mean', 'median'])

age  shoesize
mean    24.510076     32.75
median  21.250000     41.00

In [94]:
%timeit df.describe().agg(['mean', 'median'])

1.99 ms ± 83.1 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# A few more convenience methods on data frames

In [96]:
# head and tail also work!

np.random.seed(0)
df = DataFrame(np.random.randint(0, 1000, [8, 10]),
               index=list('abcdefgh'),
               columns=list('qrstuvwxyz'))
df

q    r    s    t    u    v    w    x    y    z
a  684  559  629  192  835  763  707  359    9  723
b  277  754  804  599   70  472  600  396  314  705
c  486  551   87  174  600  849  677  537  845   72
d  777  916  115  976  755  709  847  431  448  850
e   99  984  177  755  797  659  147  910  423  288
f  961  265  697  639  544  543  714  244  151  675
g  510  459  882  183   28  802  128  128  932   53
h  901  550  488  756  273  335  388  617   42  442

In [97]:
df.head()   # returns the first 5 rows

q    r    s    t    u    v    w    x    y    z
a  684  559  629  192  835  763  707  359    9  723
b  277  754  804  599   70  472  600  396  314  705
c  486  551   87  174  600  849  677  537  845   72
d  777  916  115  976  755  709  847  431  448  850
e   99  984  177  755  797  659  147  910  423  288

In [98]:
df.head(2)

q    r    s    t    u    v    w    x    y    z
a  684  559  629  192  835  763  707  359    9  723
b  277  754  804  599   70  472  600  396  314  705